# Este archivo le dice a Netlify la configuración de despliegue.

# Configuración del "Build" (construcción del sitio)
[build]
  # El "Publish directory" es la carpeta que contiene tu archivo index.html.
  # Ahora esta carpeta estará en la raíz del repositorio.
  publish = "public"
  
  # Especificamos variables de entorno para el build
  [build.environment]
    # Forzamos el uso de la versión 18 de Node.js, que es una versión estable (LTS).
    NODE_VERSION = "18"

# Configuración de las funciones serverless.
[functions]
  # El directorio de las funciones también estará en la raíz del repositorio.
  directory = "netlify/functions"

