# Este archivo le dice a Netlify la configuración de despliegue.

# Configuración del "Build" (construcción del sitio)
[build]
  # La carpeta que contiene tu archivo index.html.
  publish = "public"
  
  # Especificamos variables de entorno para el build
  [build.environment]
    # Forzamos el uso de la versión 18 de Node.js, que es una versión estable (LTS).
    NODE_VERSION = "18"

# Configuración de las funciones serverless.
[functions]
  # El directorio de las funciones.
  directory = "netlify/functions"
  
  # **MEJORA CLAVE**: Aumentamos el tiempo de espera de la función a 25 segundos.
  # Esto le da a la IA más tiempo para procesar páginas complejas.
  timeout = 25

