# Configuraci칩n para el despliegue en Netlify

[build]
  # Directorio que contiene los archivos del sitio a publicar.
  publish = "public"
  
  # Variables de entorno para el proceso de build.
  [build.environment]
    # Especifica una versi칩n estable de Node.js.
    NODE_VERSION = "18"

[functions]
  # Directorio donde se encuentran las funciones serverless.
  directory = "netlify/functions"
  
  # Aumenta el tiempo m치ximo de ejecuci칩n de las funciones a 25 segundos.
  timeout = 25
