# Este archivo le dice a Netlify la configuración de despliegue.

# Configuración del "Build" (construcción del sitio)
[build]
  # El "Publish directory" es la carpeta que contiene tu archivo index.html.
  # Asegúrate de que este nombre coincida EXACTAMENTE con el nombre de la carpeta en tu GitHub.
  publish = "EXTRAER DOCUMENTOS"

# Configuración de las funciones serverless.
[functions]
  directory = "netlify/functions"

